services:
  db:
    image: postgres:15
    container_name: tcg_pocket
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:	
      - go_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9000:80"
    networks:	
      - go_network
  go_app:
    container_name: go_app
    build: .
    ports: 
      - "8000:8000"
    depends_on:
      - db
    networks:	
      - go_network
networks:
  go_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local