INSERT INTO pokemon_cards (id, nome, card_type, tipo, estagio, geracao, ps, recuo, fraqueza) VALUES
(1, 'Bulbasaur', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 70, 1, 'Fogo'),
(2, 'Ivysaur', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 90, 2, 'Fogo'),
(3, 'Venusaur', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 160, 3, 'Fogo'),
(4, 'Venusaur EX', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 190, 3, 'Fogo'),
(5, 'Caterpie', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 50, 1, 'Fogo'),
(6, 'Metapod', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 80, 2, 'Fogo'),
(7, 'Butterfree', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 120, 1, 'Fogo'),
(8, 'Weedle', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 50, 1, 'Fogo'),
(9, 'Kakuna', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 80, 2, 'Fogo'),
(10, 'Beedrill', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 120, 1, 'Fogo'),
(11, 'Oddish', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 60, 1, 'Fogo'),
(12, 'Gloom', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 80, 2, 'Fogo'),
(13, 'Vileplume', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 140, 3, 'Fogo'),
(14, 'Paras', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 70, 1, 'Fogo'),
(15, 'Parasect', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 120, 2, 'Fogo'),
(16, 'Venonat', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 60, 1, 'Fogo'),
(17, 'Venomoth', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 80, 1, 'Fogo'),
(18, 'Bellsprout', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 60, 1, 'Fogo'),
(19, 'Weepinbell', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 90, 2, 'Fogo'),
(69, 'Horsea', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(70, 'Seadra', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 70, 1, 'Eletrico'),
(20, 'Victreebel', 'Pokemon', 'Planta', 2, 'Dominacao Genetica', 140, 2, 'Fogo'),
(21, 'Exeggcute', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 50, 1, 'Fogo'),
(22, 'Exeggutor', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 130, 3, 'Fogo'),
(23, 'Exeggutor EX', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 160, 3, 'Fogo'),
(24, 'Tangela', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 80, 2, 'Fogo'),
(25, 'Scyther', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 70, 1, 'Fogo'),
(26, 'Pinsir', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 90, 2, 'Fogo'),
(27, 'Cottonee', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 50, 1, 'Fogo'),
(28, 'Whimsicott', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 80, 1, 'Fogo'),
(29, 'Petilil', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 60, 1, 'Fogo'),
(30, 'Lilligant', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 100, 1, 'Fogo'),
(31, 'Skiddo', 'Pokemon', 'Planta', 0, 'Dominacao Genetica', 70, 1, 'Fogo'),
(32, 'Gogoat', 'Pokemon', 'Planta', 1, 'Dominacao Genetica', 70, 1, 'Fogo'),
(33, 'Charmander', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 60, 1, 'Agua'),
(34, 'Charmeleon', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 90, 2, 'Agua'),
(35, 'Charizard', 'Pokemon', 'Fogo', 2, 'Dominacao Genetica', 150, 2, 'Agua'),
(36, 'Charizard EX', 'Pokemon', 'Fogo', 2, 'Dominacao Genetica', 180, 2, 'Agua'),
(37, 'Vulpix', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 50, 1, 'Agua'),
(38, 'Ninetales', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 90, 1, 'Agua'),
(39, 'Growlithe', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 70, 1, 'Agua'),
(40, 'Arcanine EX', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 150, 2, 'Agua'),
(41, 'Ponyta', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 60, 1, 'Agua'),
(42, 'Rapidash', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 100, 1, 'Agua'),
(43, 'Magmar', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 80, 2, 'Agua'),
(44, 'Flareon', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 120, 2, 'Agua'),
(45, 'Moltres', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(46, 'Moltres EX', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 140, 2, 'Eletrico'),
(47, 'Heatmor', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 80, 1, 'Agua'),
(48, 'Salandit', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 60, 1, 'Agua'),
(49, 'Salazzle', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 90, 1, 'Agua'),
(50, 'Sizzlipede', 'Pokemon', 'Fogo', 0, 'Dominacao Genetica', 60, 1, 'Agua'),
(51, 'Centiskorch', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 130, 3, 'Agua'),
(52, 'Squirtle', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(53, 'Wartortle', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 80, 1, 'Eletrico'),
(54, 'Blastoise', 'Pokemon', 'Agua', 2, 'Dominacao Genetica', 150, 3, 'Eletrico'),
(55, 'Blastoise EX', 'Pokemon', 'Agua', 2, 'Dominacao Genetica', 180, 3, 'Eletrico'),
(56, 'Psyduck', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(57, 'Golduck', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 1, 'Eletrico'),
(58, 'Poliwag', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(59, 'Poliwhirl', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 2, 'Eletrico'),
(60, 'Poliwrath', 'Pokemon', 'Agua', 2, 'Dominacao Genetica', 150, 2, 'Eletrico'),
(61, 'Tentacool', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(62, 'Tentacruel', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 110, 2, 'Eletrico'),
(63, 'Seel', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 80, 2, 'Eletrico'),
(64, 'Dewgong', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 120, 3, 'Eletrico'),
(65, 'Shellder', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(66, 'Cloyster', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 120, 3, 'Eletrico'),
(67, 'Krabby', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 70, 2, 'Eletrico'),
(68, 'Kingler', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 120, 3, 'Eletrico'),
(71, 'Goldeen', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(72, 'Seaking', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(73, 'Staryu', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 50, 1, 'Eletrico'),
(74, 'Starmie', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 0, 'Eletrico'),
(75, 'Starmie EX', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 130, 0, 'Eletrico'),
(76, 'Magikarp', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 50, 1, 'Eletrico'),
(77, 'Gyarados', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 150, 4, 'Eletrico'),
(78, 'Lapras', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 100, 2, 'Eletrico'),
(79, 'Vaporeon', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 130, 2, 'Eletrico'),
(80, 'Omanyte', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 1, 'Eletrico'),
(81, 'Omastar', 'Pokemon', 'Agua', 2, 'Dominacao Genetica', 140, 2, 'Eletrico'),
(82, 'Articuno', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(83, 'Articuno EX', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 140, 2, 'Eletrico'),
(84, 'Ducklett', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 50, 1, 'Eletrico'),
(85, 'Swanna', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 1, 'Eletrico'),
(86, 'Froakie', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(87, 'Frogadier', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 80, 1, 'Eletrico'),
(88, 'Greninja', 'Pokemon', 'Agua', 2, 'Dominacao Genetica', 120, 1, 'Eletrico'),
(89, 'Pyukumuku', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 70, 1, 'Eletrico'),
(90, 'Bruxish', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 90, 1, 'Eletrico'),
(91, 'Snom', 'Pokemon', 'Agua', 0, 'Dominacao Genetica', 50, 1, 'Eletrico'),
(92, 'Frosmoth', 'Pokemon', 'Agua', 1, 'Dominacao Genetica', 90, 1, 'Eletrico'),
(93, 'Pikachu', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(94, 'Raichu', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 100, 1, 'Lutador'),
(95, 'Pikachu EX', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 120, 1, 'Lutador'),
(96, 'Magnemite', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(97, 'Magneton', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 80, 2, 'Lutador'),
(98, 'Voltorb', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(99, 'Electrode', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 80, 0, 'Lutador'),
(100, 'Electabuzz', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 70, 1, 'Lutador'),
(101, 'Jolteon', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 90, 1, 'Lutador'),
(102, 'Zapdos', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(103, 'Zapdos EX', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 130, 1, 'Eletrico'),
(104, 'Blitzle', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(105, 'Zebstrika', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 90, 1, 'Lutador'),
(106, 'Tynamo', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 30, 1, 'Lutador'),
(107, 'Eelektrik', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 80, 2, 'Lutador'),
(108, 'Eelektross', 'Pokemon', 'Eletrico', 2, 'Dominacao Genetica', 140, 3, 'Lutador'),
(109, 'Helioptile', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(110, 'Heliolisk', 'Pokemon', 'Eletrico', 1, 'Dominacao Genetica', 90, 1, 'Lutador'),
(111, 'Pincurchin', 'Pokemon', 'Eletrico', 0, 'Dominacao Genetica', 70, 1, 'Lutador'),
(113, 'Clefable', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 100, 1, 'Metal'),
(112, 'Clefairy', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 60, 1, 'Metal'),
(114, 'Abra', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 60, 1, 'Noturno'),
(115, 'Kadabra', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 80, 1, 'Noturno'),
(116, 'Alakazam', 'Pokemon', 'Psiquico', 2, 'Dominacao Genetica', 130, 2, 'Noturno'),
(117, 'Slowpoke', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 70, 2, 'Noturno'),
(118, 'Slowbro', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 130, 3, 'Noturno'),
(119, 'Gastly', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 60, 1, 'Noturno'),
(120, 'Haunter', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 80, 1, 'Noturno'),
(121, 'Gengar', 'Pokemon', 'Psiquico', 2, 'Dominacao Genetica', 130, 2, 'Noturno'),
(122, 'Gengar EX', 'Pokemon', 'Psiquico', 2, 'Dominacao Genetica', 170, 2, 'Noturno'),
(123, 'Drowzee', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 70, 2, 'Noturno'),
(124, 'Hypno', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 100, 2, 'Noturno'),
(125, 'Mr. Mine', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 80, 1, 'Noturno'),
(126, 'Jynx', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 80, 1, 'Noturno'),
(127, 'Mewtwo', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 120, 2, 'Noturno'),
(128, 'Mewtwo EX', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 150, 2, 'Noturno'),
(129, 'Ralts', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 60, 1, 'Noturno'),
(130, 'Kirlia', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 80, 1, 'Noturno'),
(131, 'Gardevoir', 'Pokemon', 'Psiquico', 2, 'Dominacao Genetica', 110, 2, 'Noturno'),
(132, 'Woobat', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 60, 1, 'Noturno'),
(133, 'Swoobat', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 90, 1, 'Noturno'),
(134, 'Golett', 'Pokemon', 'Psiquico', 0, 'Dominacao Genetica', 90, 3, 'Noturno'),
(135, 'Golurk', 'Pokemon', 'Psiquico', 1, 'Dominacao Genetica', 140, 4, 'Noturno'),
(136, 'Sandshrew', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 70, 1, 'Psiquico'),
(137, 'Sandslash', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 100, 2, 'Psiquico'),
(138, 'Diglett', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 50, 1, 'Planta'),
(139, 'Dugtrio', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 70, 1, 'Planta'),
(140, 'Mankey', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 60, 1, 'Psiquico'),
(141, 'Primeape', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 90, 1, 'Psiquico'),
(142, 'Machop', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 70, 2, 'Psiquico'),
(143, 'Machoke', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 100, 2, 'Psiquico'),
(144, 'Machamp', 'Pokemon', 'Lutador', 2, 'Dominacao Genetica', 150, 3, 'Psiquico'),
(145, 'Machamp EX', 'Pokemon', 'Lutador', 2, 'Dominacao Genetica', 180, 3, 'Psiquico'),
(146, 'Geodude', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 70, 2, 'Planta'),
(147, 'Graveler', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 100, 3, 'Planta'),
(148, 'Golem', 'Pokemon', 'Lutador', 2, 'Dominacao Genetica', 160, 4, 'Planta'),
(149, 'Onix', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 110, 4, 'Planta'),
(150, 'Cubone', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 60, 1, 'Planta'),
(151, 'Marowak', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 100, 1, 'Planta'),
(152, 'Marowak EX', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 140, 1, 'Planta'),
(153, 'Hitmonlee', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 80, 1, 'Psiquico'),
(154, 'Hitmonchan', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 80, 1, 'Psiquico'),
(155, 'Rhyhorn', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 80, 3, 'Planta'),
(156, 'Rhydon', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 120, 4, 'Planta'),
(157, 'Kabuto', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 90, 1, 'Planta'),
(158, 'Kabutops', 'Pokemon', 'Lutador', 2, 'Dominacao Genetica', 140, 1, 'Planta'),
(159, 'Mienfoo', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 60, 1, 'Psiquico'),
(160, 'Mienshao', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 80, 1, 'Psiquico'),
(161, 'Clobbopus', 'Pokemon', 'Lutador', 0, 'Dominacao Genetica', 80, 2, 'Psiquico'),
(162, 'Grapploct', 'Pokemon', 'Lutador', 1, 'Dominacao Genetica', 130, 3, 'Psiquico'),
(163, 'Ekans', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(164, 'Arbok', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 100, 2, 'Lutador'),
(165, 'Nidoran Femea', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(166, 'Nidorina', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 80, 1, 'Lutador'),
(167, 'Nidoqueen', 'Pokemon', 'Noturno', 2, 'Dominacao Genetica', 140, 2, 'Lutador'),
(168, 'Nidoran Macho', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(169, 'Nidorino', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 90, 2, 'Lutador'),
(170, 'Nidoking', 'Pokemon', 'Noturno', 2, 'Dominacao Genetica', 150, 3, 'Lutador'),
(171, 'Zubat', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 50, 1, 'Lutador'),
(172, 'Golbat', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 70, 1, 'Lutador'),
(173, 'Grimer', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 70, 3, 'Lutador'),
(174, 'Muk', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 130, 3, 'Lutador'),
(175, 'Koffing', 'Pokemon', 'Noturno', 0, 'Dominacao Genetica', 70, 1, 'Lutador'),
(176, 'Weezing', 'Pokemon', 'Noturno', 1, 'Dominacao Genetica', 110, 3, 'Lutador'),
(177, 'Mawile', 'Pokemon', 'Metal', 0, 'Dominacao Genetica', 70, 1, 'Fogo'),
(178, 'Pawniard', 'Pokemon', 'Metal', 0, 'Dominacao Genetica', 50, 1, 'Fogo'),
(179, 'Bisharp', 'Pokemon', 'Metal', 1, 'Dominacao Genetica', 90, 1, 'Fogo'),
(180, 'Meltan', 'Pokemon', 'Metal', 0, 'Dominacao Genetica', 60, 1, 'Fogo'),
(181, 'Melmetal', 'Pokemon', 'Metal', 1, 'Dominacao Genetica', 130, 3, 'Fogo'),
(182, 'Dratini', 'Pokemon', 'Dragao', 0, 'Dominacao Genetica', 70, 1, NULL),
(183, 'Dragonair', 'Pokemon', 'Dragao', 1, 'Dominacao Genetica', 100, 1, NULL),
(184, 'Dragonite', 'Pokemon', 'Dragao', 2, 'Dominacao Genetica', 160, 3, NULL),
(185, 'Pidgey', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(186, 'Pidgeotto', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 80, 1, 'Eletrico'),
(187, 'Pidgeot', 'Pokemon', 'Normal', 2, 'Dominacao Genetica', 130, 1, 'Eletrico'),
(188, 'Rattata', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 40, 1, 'Lutador'),
(189, 'Raticate', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 80, 1, 'Lutador'),
(190, 'Spearow', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(191, 'Fearow', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(192, 'Jigglypuff', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(193, 'Wigglytuff', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 100, 2, 'Lutador'),
(194, 'Wigglytuff EX', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 140, 2, 'Lutador'),
(195, 'Meowth', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(196, 'Persian', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 90, 1, 'Lutador'),
(197, 'Farfetch''d', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(198, 'Doduo', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Eletrico'),
(199, 'Dodrio', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 80, 1, 'Eletrico'),
(200, 'Lickitung', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 90, 3, 'Lutador'),
(201, 'Chansey', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 120, 3, 'Lutador'),
(202, 'Kangaskhan', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 100, 3, 'Lutador'),
(203, 'Tauros', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 100, 2, 'Lutador'),
(204, 'Ditto', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 70, 1, 'Lutador'),
(205, 'Eevee', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(206, 'Porygon', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 50, 1, 'Lutador'),
(207, 'Aerodactyl', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 100, 1, 'Eletrico'),
(208, 'Minccino', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 60, 1, 'Lutador'),
(209, 'Cinccino', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 90, 1, 'Lutador'),
(210, 'Wooloo', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 70, 1, 'Lutador'),
(211, 'Dubwool', 'Pokemon', 'Normal', 1, 'Dominacao Genetica', 120, 2, 'Lutador'),
(212, 'Snorlax', 'Pokemon', 'Normal', 0, 'Dominacao Genetica', 150, 4, 'Lutador'),
(213, 'Arcanine', 'Pokemon', 'Fogo', 1, 'Dominacao Genetica', 130, 2, 'Agua');

INSERT INTO habilidades (nome_habilidade, efeito_habilidade) VALUES
('Cura em Po', 'Uma vez durante o seu turno, você poderá curar 20 pontos de dano de cada um dos seus Pokemon'), 
('Armadilha Cheirosa', 'Se este Pokemon estiver no Campo Ativo, uma vez durante o seu turno, você poderá mandar 1 dos Pokemon Basicos no Banco do seu oponente para o Campo Ativo'), 
('Contra-ataque', 'Se este Pokemon estive no Campo Ativo e for danificado por um ataque dos Pokemon do se oponente cause 20 pontos de dano ao Pokemon Atacante'), 
('Armadura de Concha', 'Este Pokemon recebe -10 pontos de dano de ataques'), 
('Estrela Ninja de Agua', 'Uma vez durante o seu turno, você poderá causar 20 pontos de dano a 1 dos Pokemon do seu oponente'), 
('Carga Voltaica', 'Uma vez durante o seu turno, você poderá pegar 1 Energia Eletrica da sua Zona de Energia e ligá-la a este Pokemon'), 
('Enfeiticamento Sombrio', 'Enquanto este Pokemon estiver no Campo Ativo, o seu oponente não poderá usar nenhuma carta de Apoiador da não dele'), 
('Pendulo do Sono', 'Uma vez durante o seu turno você poderá jogar uma moeda. Se sair cara o Pokemon Ativo do seu oponente agora estará Adormecido'),
('Sombra Psiquica', 'Uma vez por turno, você poderá pegar 1 Energia Psiquica da sua Zona de Energia e liga-la ao Pokemon Psiquico no Campo Ativo'), 
('Vazamento de Gas', 'Uma vez durante o seu turno, se este Pokemon estiver no Campo Ativo, voce poderá deixar o Pokemon Ativo do seu oponente Envenenado'), 
('Camada Resistente', 'Este Pokemon recebe -20 pontos de dano de ataques'),
('Rechacar', 'Uma vez durante o seu turno voce poderá mandar o Pokemon Ativo do seu oponente para o Banco'), 
('Escaneamento de Dados', 'Uma vez durante o seu turno, voce poderá olhar a carta de cima do seu baralho');

INSERT INTO item (id, nome, card_type, efeito) VALUES
(1, 'Fossil Espiral', 'Item', ARRAY['Jogue essa carta como se fosse um Pokemon No Banco. Enquanto estiver em jogo, conte como um Pokemon do tipo Incolor com 40 HP. Se for nocauteado, seu oponente compra um premio.']),
(2, 'Fossil Cupula', 'Item', ARRAY['Jogue essa carta como se fosse um Pokemon No Banco. Enquanto estiver em jogo, conte como um Pokemon do tipo Incolor com 40 HP. Se for nocauteado, seu oponente compra um premio.']),
(3, 'Ambar Velho', 'Item', ARRAY['Jogue essa carta como se fosse um Pokemon No Banco. Enquanto estiver em jogo, conte como um Pokemon do tipo Incolor com 40 HP. Se for nocauteado, seu oponente compra um premio.']);

INSERT INTO ataques (nome_ataque, dano_ataque, custo_ataque, efeito_ataque) VALUES
('Chicote de Vinha', 40, ARRAY['Planta','Normal'], NULL),
('Folha Navalha', 60, ARRAY['Planta','Normal','Normal'], NULL),
('Megadreno', 80, ARRAY['Planta','Planta','Normal','Normal'], 'Cure 30 pontos de dano deste Pokemon'),
('Florescimento Gigante', 100, ARRAY['Planta','Planta','Normal','Normal'], 'Cure 30 pontos de dano deste Pokemon'),
('Encontre um Amigo', 0, ARRAY['Normal'], 'Coloque 1 Pokemon Planta aleatorio do seu baralho na sua mao'),
('Picada', 30, ARRAY['Normal','Normal'], NULL),
('Lufada de Vento', 60, ARRAY['Planta','Normal','Normal'], NULL),
('Ferroada', 20, ARRAY['Planta'], NULL),
('Picada 1', 30, ARRAY['Planta'], NULL),
('Ferroada Afiada', 70, ARRAY['Planta'], NULL),
('Babar', 40, ARRAY['Planta','Normal'], NULL),
('Ariete', 20, ARRAY['Planta'], NULL),
('Odor Calmante', 80, ARRAY['Planta','Planta','Normal'], 'O Pokemon Ativo do seu oponente agora esta Adormecido'),
('Arranhao', 30, ARRAY['Planta','Normal'], NULL),
('Talho', 80, ARRAY['Planta','Planta','Normal'], NULL),
('Investida', 20, ARRAY['Planta'], NULL),
('Po Venenoso', 30, ARRAY['Planta'], 'O Pokemon Ativo do seu oponente agora está Envenenado'),
('Chicote de Vinha 1', 20, ARRAY['Planta'], NULL),
('Folha Navalha 1', 40, ARRAY['Planta','Normal'], NULL),
('Chicote de Vinha 2', 60, ARRAY['Planta','Normal'], NULL),
('Bomba de Sementes', 20, ARRAY['Planta'], NULL),
('Pisotear', 30, ARRAY['Planta'], 'Jogue uma moeda. Se sair cara, este ataque cuasará 30 pontos de dano a mais'),
('Balanço Tropical', 40, ARRAY['Planta'], 'Jogue uma moeda. Se sair cara, este ataque cuasará 40 pontos de dano a mais'),
('Absorcao', 40, ARRAY['Planta','Normal'], 'Cure 10 pontos de dano deste Pokemon'),
('Foice Afiada', 30, ARRAY['Planta'], NULL),
('Chifre Duplo', 50, ARRAY['Planta','Planta'], 'Jogue 2 moeda. Este ataque causa 50 pontos de dano para cada cara'),
('Conectar', 50, ARRAY['Normal'], NULL),
('Golpe de Colisao Rolante', 40, ARRAY['Normal'], NULL),
('Borrão', 10, ARRAY['Planta'], 'Cure 10 pontos de dano deste Pokemon'),
('Estoque de Folha', 50, ARRAY['Planta','Planta'], 'Pegue 1 Energia Planta da sua zona de Energia e ligue-a a 1 dos seus Pokemon Planta no Banco'),
('Barbatana Cortante', 10, ARRAY['Normal'], NULL),
('Folha Navalha 3', 70, ARRAY['Planta','Normal','Normal'], NULL),
('Brasa', 30, ARRAY['Fogo'], 'Descarte 1 Energia Fogo deste Pokemon'),
('Garras de Fogo', 60, ARRAY['Fogo','Normal','Normal'], NULL),
('Chama Furacao', 150, ARRAY['Fogo','Fogo','Normal','Normal'], 'Descarte 2 Energia Fogo deste Pokemon'),
('Talho 1', 60, ARRAY['Fogo','Normal','Normal'], NULL),
('Tempestade Carmim', 200, ARRAY['Fogo','Fogo','Normal','Normal'], 'Descarte 2 Energia Fogo deste Pokemon'),
('Cauda Chicote', 0, ARRAY['Normal'], 'Jogue uma moeda. Se sair cara, o Pokemon Defensor não poderá atacar durante o proximo turno do se oponente'),
('Lança-Chamas', 90, ARRAY['Fogo','Fogo'], 'Descarte 1 Energia Fogo deste Pokemon'),
('Mordida', 20, ARRAY['Normal','Normal'], NULL),
('Investida Infernal', 120, ARRAY['Fogo','Fogo','Normal'], 'Este Pokemon também causa 20 pontos de dano a si mesmo'),
('Chama', 20, ARRAY['Fogo'], NULL),
('Crina de Fogo', 40, ARRAY['Fogo'], NULL),
('Soco de Magma', 50, ARRAY['Fogo'], NULL),
('Lança-Chama 1', 110, ARRAY['Fogo','Normal','Normal'], 'Descarte 1 Energia Fogo deste Pokemon'),
('Ataque do Ceu', 130, ARRAY['Fogo','Normal','Normal'], 'Jogue uma moeda. Se sair coroa, este ataque não fará nada'),
('Danca Infernal', 0, ARRAY['Fogo'], 'Jogue 3 moeda. Pegue uma quantidade de Energia Fogo da sua Zona de Energia equivalente ao numero de caras e ligue aos seus Pokemon Fogo no Banco como desejar'),
('Raio de Calor', 70, ARRAY['Fogo','Normal','Normal'], NULL),
('Combustao', 30, ARRAY['Fogo'], NULL),
('Arranhao 1', 20, ARRAY['Fogo'], NULL),
('Roido', 10, ARRAY['Normal'], NULL),
('Rajada de Fogo', 10, ARRAY['Fogo','Normal','Normal','Normal'], 'Descarte 1 Energia Fogo deste Pokemon'),
('Revolver d''Agua', 20, ARRAY['Agua'], NULL),
('Onda Borrifante', 40, ARRAY['Agua','Normal'], NULL),
('Jato d''Agua', 80, ARRAY['Agua','Agua','Normal'], 'Se este Pokemon tiver pelo menos 2 Energia Agua extra ligadas a ele, este ataque causará 60 pontos de dano a mais'),
('Surfar', 40, ARRAY['Agua','Normal'], NULL),
('Bazuca d''Agua', 100, ARRAY['Agua','Agua','Normal'], 'Se este Pokemon tiver pelo menos 2 Energia Agua extra ligadas a ele, este ataque causará 60 pontos de dano a mais'),
('Dor de Cabeca', 10, ARRAY['Normal'], 'Seu oponente não poderá usar nenhuma carta de Apoiador durante o proximo turno dele'),
('Aqua Gume', 70, ARRAY['Agua','Agua'], NULL),
('Soco com Punho', 40, ARRAY['Normal','Normal'], NULL),
('Megassoco', 80, ARRAY['Agua','Normal','Normal'], NULL),
('Tapinha', 20, ARRAY['Agua'], NULL),
('Tentaculos Venenosos', 50, ARRAY['Agua','Normal'], 'O Pokemon Ativo do seu oponente agora está Envenenado'),
('Cabecada', 30, ARRAY['Normal','Normal'], NULL),
('Surfar 1', 90, ARRAY['Agua','Agua','Agua'], NULL),
('Tapa de Lingua', 20, ARRAY['Agua'], NULL),
('Surfar 2', 70, ARRAY['Agua'], NULL),
('Agarramento Compressor', 40, ARRAY['Agua','Normal'], NULL),
('Nocaute Caranguejo', 80, ARRAY['Agua','Agua','Normal'], 'Jogue 2 moedas. Se as duas sairem cara, este ataque causará 80 pontos de danos a mais'),
('Flecha d''Agua', 50, ARRAY['Agua'], 'Este ataque causar 50 pontos de dano a 1 dos Pokemon do seu oponente'),
('Baque', 10, ARRAY['Agua'], NULL),
('Chifre Perigoso', 80, ARRAY['Agua'], 'Jogue uma Moeda. Se sair coroa, este ataque não fará nada'),
('Estalo', 20, ARRAY['Agua'], NULL),
('Hidroborrifada', 90, ARRAY['Agua','Agua'], NULL),
('Borrifada', 90, ARRAY['Normal'], NULL),
('Hiper-raio', 100, ARRAY['Agua','Agua','Agua','Agua'], 'Descarte 1 Energia aleatoria do Pokemon Ativo do seu oponente'),
('Jato d''Agua 1', 20, ARRAY['Agua'], 'Se este Pokemon tiver pelo menos 3 Energia Agua Extras ligada a ele, este Ataque causará 70 pontos de dano a mais'),
('Dreno de Bolha', 60, ARRAY['Agua','Normal','Normal'], 'Cure 30 pontos de dano deste Pokemon'),
('Revolver d''Agua 1', 40, ARRAY['Agua'], NULL),
('Redemoinho Ancestral', 70, ARRAY['Agua'], 'Durante o proximo turno do seu oponente, o Pokemon Defensor não poderá atacar'),
('Raio Congelante', 60, ARRAY['Agua','Agua','Normal'], 'Jogue uma moeda, Se sair cara, o Pokemon Ativo do seu oponente agora estará Paralisado'),
('Asa de Gelo', 40, ARRAY['Agua','Normal'], NULL),
('Nevasca', 80, ARRAY['Agua','Agua','Agua'], 'Este ataque tambem causa 10 pontos de dano a cada Pokemon no Banco do seu oponente'),
('Asa', 30, ARRAY['Normal','Normal'], NULL),
('Ataque de Asa', 70, ARRAY['Normal','Normal','Normal'], NULL),
('Baque 1', 10, ARRAY['Normal'], NULL),
('Gotejo', 30, ARRAY['Normal'], NULL),
('Golpe de Nevoa', 60, ARRAY['Agua','Normal'], NULL),
('Chuva Borrifante', 30, ARRAY['Agua'], NULL),
('Segundo Golpe', 10, ARRAY['Agua','Normal'], 'Se o Pokemon Ativo do seu oponente estiver danificado este ataque causará 60 pontos de dano a mais'),
('Ariete 1', 10, ARRAY['Normal'], NULL),
('Neve em Po', 40, ARRAY['Agua','Normal'], 'O Pokemon Ativo do seu oponente agora está Adormecido'),
('Roida', 20, ARRAY['Eletrico'], NULL),
('Relampago', 140, ARRAY['Eletrico','Eletrico','Eletrico'], 'Descarte todas as Energia deste Pokemon'),
('Circuito Circular', 30, ARRAY['Eletrico','Eletrico'], 'Este Pokemon causa 30 pontos de dano para cada Pokemon Eletrico no seu Banco'),
('Bola de Raios', 20, ARRAY['Eletrico'], NULL),
('Ataque Giratorio', 60, ARRAY['Eletrico','Normal','Normal','Normal'], NULL),
('Investida 1', 20, ARRAY['Eletrico'], NULL),
('Bola Eletrica', 80, ARRAY['Eletrico','Eletrico'], NULL),
('Soco Trovoada', 40, ARRAY['Eletrico','Eletrico'], 'Jogue uma moeda. Se sair cara, este ataque causará 40 pontos de dano a mais, se sair coroa, este Pokemon tambem causará 20 pontos de dano a si mesmo'),
('Missil de Espinhos', 40, ARRAY['Eletrico','Normal'], 'Jogue 4 moedas. Este Ataque causa 40 pontos de dano para cada cara'),
('Bicada', 20, ARRAY['Eletrico'], NULL),
('Furacao Trovejante', 50, ARRAY['Eletrico','Eletrico','Eletrico'], 'Jogue 4 moedas. Este ataque causa 50 pontos de dano para cada cara'),
('Chute Zap', 20, ARRAY['Eletrico'], NULL),
('Lanca do Trovao', 30, ARRAY['Eletrico'], 'Este ataque causa 30 pontos de dano 1 dos Pokemon do seu oponente'),
('Carga Pequenina', 30, ARRAY['Eletrico'], NULL),
('Raio de Cabeca', 40, ARRAY['Eletrico'], NULL),
('Surra de Cauda', 20, ARRAY['Eletrico'], NULL),
('Ataque Rapido', 40, ARRAY['Normal','Normal'], 'Jogue uma moeda. Se sair cara, este ataque causará 40 pontos de dano a mais'),
('Trovoada de Choque', 30, ARRAY['Eletrico','Eletrico'], 'Jogue uma moeda. Se sair cara, o Pokemon ativo do seu oponente agora esta Paralisado'),
('Tapa', 20, ARRAY['Psiquico'], NULL),
('Tiro Magico', 40, ARRAY['Psiquico'], NULL),
('Teleporto', 0, ARRAY['Normal'], 'Troque este Pokemon por 1 dos seus Pokemon no banco'),
('Super-raio Psiquico', 60, ARRAY['Psiquico','Normal','Normal'], NULL),
('Psiquico', 60, ARRAY['Psiquico','Normal','Normal'], 'Este Ataque causa 30 pontos de dano a mais para cada Energia ligada ao Pokemon Ativo do seu oponente'),
('Surra de Cauda 1', 30, ARRAY['Psiquico','Normal'], NULL),
('Super-raio Psiquico 1', 80, ARRAY['Psiquico','Psiquico','Normal'], NULL),
('Gas Asfixiante', 60, ARRAY['Psiquico'], NULL),
('Fogo Fatuo', 30, ARRAY['Psiquico'], NULL),
('Azucrinar', 50, ARRAY['Psiquico'], 'Seu oponente não poderá usar nenhuma carta de Apoiador durante o proximo turno dele'),
('Tiro Assustador', 100, ARRAY['Psiquico','Psiquico','Psiquico'], NULL),
('Resmungo', 30, ARRAY['Psiquico','Normal'], NULL),
('Soco Psiquico', 50, ARRAY['Psiquico','Psiquico','Normal'], NULL),
('Ataque Barreira', 30, ARRAY['Psiquico','Normal'], 'Durante o proximo turno do seu oponente, este Pokemon receberá -20 pontos de dano de ataques'),
('Psiquico 2', 30, ARRAY['Psiquico','Normal'], 'Este Ataque causa 20 pontos de dano a mais para cada Energia ligada ao Pokemon Ativo do seu oponente'),
('Explosao Poderosa', 120, ARRAY['Psiquico','Psiquico','Normal','Normal'], 'Descarte 2 Energia Psiquico deste Pokemon'),
('Esfera Psiquica', 50, ARRAY['Psiquico','Normal'], NULL),
('Controle Psiquico', 150, ARRAY['Psiquico','Psiquico','Normal','Normal'], 'Descarte 2 Energia Psiquico deste Pokemon'),
('Estalo 1', 30, ARRAY['Psiquico','Normal'], NULL),
('Tiro Psiquico', 60, ARRAY['Psiquico','Psiquico','Normal'], NULL),
('Estampa de Coracao', 60, ARRAY['Psiquico','Normal'], NULL),
('Megassoco 1', 50, ARRAY['Psiquico','Normal','Normal'], NULL),
('Laço Duplo', 100, ARRAY['Psiquico','Psiquico','Normal','Normal'], 'Jogue 2 moedas. Este ataque causa 100 pontos de dano para cada cara'),
('Arranaho 1', 10, ARRAY['Lutador'], NULL),
('Talho 2', 70, ARRAY['Lutador','Lutador'], NULL),
('Tapa de Lama', 20, ARRAY['Lutador'], NULL),
('Cavar', 40, ARRAY['Lutador'], 'Jogue uma moeda. Se sair cara, durante o proximo turno do seu oponente, previna todo o dano e os efeitos de ataques causados a este pokemon'),
('Rateira', 20, ARRAY['Lutador'], NULL),
('Devolver Ataque', 40, ARRAY['Lutador'], 'Se este Pokemon estiver danificado, este ataque causará 60 pontos de dano a mais'),
('Forca', 50, ARRAY['Lutador','Lutador'], NULL),
('Arremesso Sismico', 100, ARRAY['Lutador','Lutador','Lutador'], NULL),
('Megassoco 2', 120, ARRAY['Lutador','Lutador','Lutador'], NULL),
('Investida 2', 20, ARRAY['Lutador'], NULL),
('Rolagem', 70, ARRAY['Lutador','Normal','Normal'], NULL),
('Faca de Dois Gumes', 150, ARRAY['Lutador','Normal','Normal','Normal'], 'Este Pokemon também causa 50 pontos de dano a si mesmo'),
('Aperto de Terra', 70, ARRAY['Lutador','Lutador','Lutador'], NULL),
('Rosnadura', 0, ARRAY['Normal'], 'Durante o proximo turno do seu oponente, os ataques usado pelo Pokemon Defensor causarão -20 pontos de dano'),
('Surra de Osso', 40, ARRAY['Lutador'], NULL),
('Ossomerangue', 80, ARRAY['Lutador','Lutador'], 'Jogue 2 moedas. Este ataque causa 80 pontos de dano para cada cara'),
('Chute Esticado', 30, ARRAY['Lutador'], 'Este ataque causa 30 pontos de dano a 1 dos Pokemon no Banco do seu oponente'),
('Murro', 30, ARRAY['Lutador'], NULL),
('Investida 3', 60, ARRAY['Lutador','Lutador','Normal'], NULL),
('Chifre Broca', 100, ARRAY['Lutador','Lutador','Lutador','Normal'], NULL),
('Ataque Carapaca', 40, ARRAY['Lutador'], NULL),
('Suga-vidas', 50, ARRAY['Lutador'], 'Cure este Pokemon a mesma quantidade de dano que voce causou ao Pokemon Ativo do seu oponente'),
('Pancada', 20, ARRAY['Normal'], NULL),
('Chute Espiral', 40, ARRAY['Normal'], NULL),
('Soco com Punho 1', 30, ARRAY['Lutador','Normal'], NULL),
('Jogar de Volta', 70, ARRAY['Lutador','Lutador','Normal'], 'Mande o Pokemon Ativo do seu oponente para o Banco'),
('Mordida 1', 20, ARRAY['Noturno'], NULL),
('Quina', 60, ARRAY['Noturno','Normal'], 'Durante o proximo turno do seu oponete, o Pokemon Defensor não poderá recuar'),
('Chamar a Familia', 0, ARRAY['Noturno'], 'Coloque 1 Nidoran Macho aleatorio do seu baralho no seu Banco'),
('Ataque de Amor', 80, ARRAY['Noturno','Noturno','Normal'], 'Este ataque causa 50 pontos de dano a mais para cada um dos seus Nidoking no Banco'),
('Bicada 1', 20, ARRAY['Noturno'], NULL),
('Ataque de Chifre', 40, ARRAY['Noturno','Normal'], NULL),
('Chifre Venenoso', 90, ARRAY['Noturno','Noturno','Normal'], 'O Pokemon Ativo do seu oponente agora esta Envenenado'),
('Planeio', 10, ARRAY['Normal'], NULL),
('Gás Venenoso', 10, ARRAY['Noturno'], 'O Pokemon Ativo do seu oponente agora esta Envenenado'),
('Venochoque', 70, ARRAY['Noturno','Noturno','Normal'], 'Se o Pokemon Ativo do seu oponente estiver Envenenado, este ataque causará 50 pontos de dano a mais'),
('Gas Asfixiante 1', 20, ARRAY['Noturno'], NULL),
('Investida 4', 30, ARRAY['Noturno'], NULL),
('Mastigada', 20, ARRAY['Metal'], 'Jogue uma moeda. Se sair cara, descarte 1 energia aleatoria do Pokemon ativo do seu oponente'),
('Perfurar', 30, ARRAY['Metal'], NULL),
('Garra de Metal', 70, ARRAY['Metal'], NULL),
('Acumular', 0, ARRAY['Metal'], 'Pegue uma Energia Metal da usa Zona de Energia e ligue-a a este Pokemon'),
('Ariete 2', 40, ARRAY['Agua','Eletrico'], NULL),
('Ataque de Cauda', 80, ARRAY['Agua','Eletrico','Normal'], NULL),
('Impacto Pesado', 120, ARRAY['Metal','Metal','Metal','Normal'], NULL),
('Meteoro do Dragao', 200, ARRAY['Agua','Eletrico','Normal','Normal'], '4 vezes um Pokemon do oponente é escolhido aleatoriamente. Para cada vez que um Pokemon for escolhido, causará 50 pontos de dano a ele'),
('Lufada de Vento 1', 30, ARRAY['Normal'], NULL),
('Ataque de Asa 1', 70, ARRAY['Normal','Normal'], NULL),
('Roida 1', 20, ARRAY['Normal'], NULL),
('Mordida 2', 40, ARRAY['Normal'], NULL),
('Bicada 2', 20, ARRAY['Normal'], NULL),
('Furacao', 50, ARRAY['Normal','Normal'], 'Jogue uma moeda. Se sair cara, descarte uma Energia aleatoria do Pokemon Ativo do seu oponente.'),
('Pancada 1', 30, ARRAY['Normal','Normal'], NULL),
('Hipervoz', 60, ARRAY['Normal','Normal'], NULL),
('Cancao Sonolenta', 80, ARRAY['Normal','Normal','Normal'], 'O Pokemon Ativo do seu oponente agora esta Adormecido'),
('Dia de Pagamento', 10, ARRAY['Normal'], 'Compre 1 carta'),
('Garra Sombria', 40, ARRAY['Normal','Normal'], 'Jogue uma moeda. Se sair cara, descarta uma carta aleatoria da mao do seu oponente'),
('Golpe Alho Poro', 40, ARRAY['Normal'], NULL),
('Bica Broca', 40, ARRAY['Normal'], NULL),
('Lambida Continua', 60, ARRAY['Normal','Normal','Normal'], 'Jogue uma moeda ate sair coroa. Este Ataque causa 60 pontos de dano para cada cara'),
('Tapinha 1', 60, ARRAY['Normal','Normal','Normal'], NULL),
('Soco Estonteante', 30, ARRAY['Normal'], 'Jogue 2 moeda. Este ataque causa 30 pontos de dano para cada cara'),
('Ataque de Chifre 1', 50, ARRAY['Normal','Normal'], NULL),
('Copia Sem Limite', 0, ARRAY['Normal'], 'Escolha 1 dos ataques dos Pokemon do seu oponente e use como este ataque. Se este Pokemon nao tiver a Energia necessario para atacar, este ataque nao fará nada'),
('Investida 5', 20, ARRAY['Normal'], NULL),
('Afiar', 20, ARRAY['Normal'], NULL),
('Ataque de Asa Primitivo', 0, ARRAY['Normal','Normal'], 'Jogue uma moeda. Se sair cara, seu oponente embaralhará o Pokemon Ativo dele no baralho dele'),
('Fazer a Ola', 30, ARRAY['Normal','Normal','Normal'], 'Este ataque causa 30 pontos de dano para cada um dos seus Pokemon no Banco'),
('Investida 6', 30, ARRAY['Normal','Normal'], NULL),
('Golpe de Colisao Rolante 1', 80, ARRAY['Normal','Normal','Normal'], NULL),
('Rolagem 1', 70, ARRAY['Normal','Normal','Normal','Normal'], NULL),
('Golpe de Colisao Aquecida', 130, ARRAY['Fogo','Fogo','Normal'], 'Este Pokemon tambem causa 20 pontos de dano a si mesmo');

INSERT INTO apoiadores (id, nome, card_type, efeito) VALUES
(1, 'Erica', 'Apoiador', 'Cure 50 pontos de dano de 1 dos seus Pokemon Planta'),
(2, 'Misty', 'Apoiador', 'Escolha 1 dos Seus Pokemon Agua, e jogue uma moeda ate sair coroa. Para cada cara, pegue uma Energia Agua da usa Zona de Energia e ligue-a àquele Pokemon'),
(3, 'Blaine', 'Apoiador', 'Durante este turno, os ataques usados pelos seus Ninetales, Rapidash ou Magmar causam +30 pontos de dano ao Pokemon Ativo do seu oponente'),
(4, 'Koga', 'Apoiador', 'Coloque seu Muk ou Weezing do Campo Ativo na sua mao'),
(5, 'Giovanni', 'Apoiador', 'Durante este turno, os ataques usados pelos seus Pokemon causam +10 pontos de dano ao Pokemon Ativo do seu oponente'),
(6, 'Brock', 'Apoiador', 'Pegue 1 Energia Lutador da sua Zona de Energia e ligue-a a Golem ou Onix'),
(7, 'Sabrina', 'Apoiador', 'Mande o Pokemon Ativo do seu oponente para o Banco'),
(8, 'Ten. Surge', 'Apoiador', 'Move todas as Energia Eletrica dos seus Pokemon no Banco para seu Raichu, Eletrode ou Electabuzz no Campo Ativo');

INSERT INTO pokemon_ataque (id_pokemon, ataque) VALUES
(1, 'Chicote de Vinha'),
(2, 'Folha Navalha'),
(3, 'Megadreno'),
(4, 'Folha Navalha'),
(4, 'Florescimento Gigante'),
(5, 'Encontre um Amigo'),
(6, 'Picada'),
(7, 'Lufada de Vento'),
(8, 'Ferroada'),
(9, 'Picada 1'),
(10, 'Ferroada Afiada'),
(11, 'Ariete'),
(12, 'Babar'),
(13, 'Odor Calmante'),
(14, 'Arranhao'),
(15, 'Talho'),
(16, 'Investida'),
(17, 'Po Venenoso'),
(18, 'Chicote de Vinha 1'),
(19, 'Folha Navalha 1'),
(20, 'Chicote de Vinha 2'),
(21, 'Bomba de Sementes'),
(22, 'Pisotear'),
(23, 'Balanço Tropical'),
(24, 'Absorcao'),
(25, 'Foice Afiada'),
(26, 'Chifre Duplo'),
(27, 'Conectar'),
(28, 'Golpe de Colisao Rolante'),
(29, 'Borrão'),
(30, 'Estoque de Folha'),
(31, 'Estoque de Folha'),
(32, 'Folha Navalha 3'),
(33, 'Brasa'),
(34, 'Garras de Fogo'),
(35, 'Chama Furacao'),
(36, 'Talho 1'),
(36, 'Tempestade Carmim'),
(37, 'Cauda Chicote'),
(38, 'Lança-Chamas'),
(39, 'Mordida'),
(40, 'Investida Infernal'),
(41, 'Chama'),
(42, 'Crina de Fogo'),
(43, 'Soco de Magma'),
(44, 'Lança-Chama 1'),
(45, 'Ataque do Ceu'),
(46, 'Danca Infernal'),
(46, 'Raio de Calor'),
(47, 'Combustao'),
(48, 'Arranhao 1'),
(49, 'Garras de Fogo'),
(50, 'Roido'),
(51, 'Rajada de Fogo'),
(52, 'Revolver d''Agua'),
(53, 'Onda Borrifante'),
(54, 'Jato d''Agua'),
(55, 'Surfar'),
(55, 'Bazuca d''Agua'),
(56, 'Dor de Cabeca'),
(57, 'Aqua Gume'),
(58, 'Barbatana Cortante'),
(59, 'Soco com Punho'),
(60, 'Megassoco'),
(61, 'Tapinha'),
(62, 'Tentaculos Venenosos'),
(63, 'Cabecada'),
(64, 'Surfar 1'),
(65, 'Tapa de Lingua'),
(66, 'Surfar 2'),
(67, 'Agarramento Compressor'),
(68, 'Nocaute Caranguejo'),
(69, 'Revolver d''Agua'),
(70, 'Flecha d''Agua'),
(71, 'Baque'),
(72, 'Chifre Perigoso'),
(73, 'Estalo'),
(74, 'Onda Borrifante'),
(75, 'Hidroborrifada'),
(76, 'Borrifada'),
(77, 'Hiper-raio'),
(78, 'Jato d''Agua 1'),
(79, 'Dreno de Bolha'),
(80, 'Revolver d''Agua 1'),
(81, 'Redemoinho Ancestral'),
(82, 'Raio Congelante'),
(83, 'Asa de Gelo'),
(83, 'Nevasca'),
(84, 'Asa'),
(85, 'Ataque de Asa'),
(86, 'Baque 1'),
(87, 'Gotejo'),
(88, 'Golpe de Nevoa'),
(89, 'Chuva Borrifante'),
(90, 'Segundo Golpe'),
(91, 'Ariete 1'),
(92, 'Neve em Po'),
(93, 'Roida'),
(94, 'Relampago'),
(95, 'Circuito Circular'),
(96, 'Bola de Raios'),
(97, 'Ataque Giratorio'),
(98, 'Investida 1'),
(99, 'Bola Eletrica'),
(100, 'Soco Trovoada'),
(101, 'Missil de Espinhos'),
(102, 'Missil de Espinhos'),
(103, 'Bicada'),
(103, 'Furacao Trovejante'),
(104, 'Chute Zap'),
(105, 'Lanca do Trovao'),
(106, 'Carga Pequenina'),
(107, 'Raio de Cabeca'),
(108, 'Raio de Cabeca'),
(109, 'Surra de Cauda'),
(110, 'Ataque Rapido'),
(111, 'Trovoada de Choque'),
(112, 'Tapa'),
(113, 'Tiro Magico'),
(114, 'Teleporto'),
(115, 'Super-raio Psiquico'),
(116, 'Psiquico'),
(117, 'Surra de Cauda 1'),
(118, 'Super-raio Psiquico 1'),
(119, 'Gas Asfixiante'),
(120, 'Fogo Fatuo'),
(121, 'Azucrinar'),
(122, 'Tiro Assustador'),
(123, 'Resmungo'),
(124, 'Soco Psiquico'),
(125, 'Ataque Barreira'),
(126, 'Psiquico 2'),
(127, 'Explosao Poderosa'),
(128, 'Esfera Psiquica'),
(128, 'Controle Psiquico'),
(129, 'Ariete 1'),
(130, 'Estalo 1'),
(131, 'Tiro Psiquico'),
(132, 'Roida'),
(133, 'Estampa de Coracao'),
(134, 'Megassoco 1'),
(135, 'Laço Duplo'),
(136, 'Arranaho 1'),
(137, 'Talho 2'),
(138, 'Tapa de Lama'),
(139, 'Cavar'),
(140, 'Rateira'),
(141, 'Devolver Ataque'),
(142, 'Soco com Punho'),
(143, 'Forca'),
(144, 'Arremesso Sismico'),
(145, 'Megassoco 2'),
(146, 'Investida 2'),
(147, 'Rolagem'),
(148, 'Faca de Dois Gumes'),
(149, 'Aperto de Terra'),
(150, 'Rosnadura'),
(151, 'Surra de Osso'),
(152, 'Ossomerangue'),
(153, 'Chute Esticado'),
(154, 'Murro'),
(155, 'Investida 3'),
(156, 'Chifre Broca'),
(157, 'Ataque Carapaca'),
(158, 'Suga-vidas'),
(159, 'Pancada'),
(160, 'Chute Espiral'),
(161, 'Soco com Punho 1'),
(162, 'Jogar de Volta'),
(163, 'Mordida 1'),
(164, 'Quina'),
(165, 'Chamar a Familia'),
(166, 'Mordida 1'),
(167, 'Ataque de Amor'),
(168, 'Bicada 1'),
(169, 'Ataque de Chifre'),
(170, 'Chifre Venenoso'),
(171, 'Planeio'),
(172, 'Ataque de Asa'),
(173, 'Gás Venenoso'),
(174, 'Venochoque'),
(175, 'Gas Asfixiante 1'),
(176, 'Investida 4'),
(177, 'Mastigada'),
(178, 'Perfurar'),
(179, 'Garra de Metal'),
(180, 'Acumular'),
(182, 'Ariete 2'),
(183, 'Ataque de Cauda'),
(181, 'Impacto Pesado'),
(184, 'Meteoro do Dragao'),
(185, 'Lufada de Vento'),
(186, 'Lufada de Vento 1'),
(187, 'Ataque de Asa 1'),
(188, 'Roida 1'),
(189, 'Mordida 2'),
(190, 'Bicada 2'),
(191, 'Furacao'),
(192, 'Pancada 1'),
(193, 'Hipervoz'),
(194, 'Cancao Sonolenta'),
(195, 'Dia de Pagamento'),
(196, 'Garra Sombria'),
(197, 'Golpe Alho Poro'),
(198, 'Bicada 2'),
(199, 'Bica Broca'),
(200, 'Lambida Continua'),
(201, 'Tapinha 1'),
(202, 'Soco Estonteante'),
(203, 'Ataque de Chifre 1'),
(204, 'Copia Sem Limite'),
(205, 'Investida 5'),
(206, 'Afiar'),
(207, 'Ataque de Asa Primitivo'),
(208, 'Ataque de Cauda'),
(209, 'Fazer a Ola'),
(210, 'Investida 6'),
(211, 'Golpe de Colisao Rolante 1'),
(212, 'Rolagem 1'),
(213, 'Golpe de Colisao Aquecida');

INSERT INTO pokemon_habilidade (id_pokemon, habilidade) VALUES
(7, 'Cura em Po'),
(20, 'Armadilha Cheirosa'),
(60, 'Contra-ataque'),
(66, 'Armadura de Concha'),
(88, 'Estrela Ninja de Agua'),
(97, 'Carga Voltaica'),
(122, 'Enfeiticamento Sombrio'),
(124, 'Pendulo do Sono'),
(131, 'Sombra Psiquica'),
(176, 'Vazamento de Gas'),
(181, 'Camada Resistente'),
(187, 'Rechacar'),
(206, 'Escaneamento de Dados');
